FROM node:18-alpine

WORKDIR /sbh-neuroglancer

# Install dependencies
COPY sbh-neuroglancer/package.json package.json
COPY sbh-neuroglancer/package-lock.json package-lock.json
RUN npm install

# Copy application
COPY sbh-neuroglancer sbh-neuroglancer

# Expose port
EXPOSE 8080

CMD ["npm", "run", "dev-server-python"]
