FROM python:3.10-slim

WORKDIR /sbh-neuroglancer

RUN apt-get update && apt-get install -y curl nodejs npm && rm -rf /var/lib/apt/lists/*

# Create a virtual environment
RUN python -m venv .venv

COPY sbh-neuroglancer/requirements.txt requirements.txt
RUN .venv/bin/pip install --upgrade pip && .venv/bin/pip install -r requirements.txt

COPY sbh-neuroglancer/ .

# Install Neuroglancer in editable mode
RUN .venv/bin/pip install -e .

ENV FLASK_APP=run_neuroglancer.py
ENV FLASK_ENV=production

EXPOSE 5002 5003
CMD [".venv/bin/python", "run_neuroglancer.py"]
